# -*- coding: utf-8 -*-
"""Копия блокнота "visc_python_assignment_probability.ipynb"

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Lum5WxSbqk32Jn-VYTFJxWKcCfOKOXt

## Assignment: Probability

### As business context for this assignment, you work for a company that sells personal printers.  When customers buy a printer, they receive a one year warranty on parts and service.  If the printer is defective, the company pays for the repairs.  Sometimes the company handle the repairs themselves, and sometimes they pay an outside firm to do so.

### Case for Poisson Distribution.
"""

# Import SciPy to assist with our probability calculations.
from scipy import stats

# Create a Poisson random variable.
# Monthly average = 175
X = stats.poisson(175)

# The probability of 200 or fewer warranty claims next month.
X.cdf(200)

# The probability of more than 200 claims next month.
1 - X.cdf(200)

# The probablity of exactly 175 claims next month.
X.pmf(175)

"""### Case for binomial distribution."""

# Create a binomial random variables (Y)
Y = stats.binom(300, 0.25)

# The probability of exactly 70 of the next 300 warranty claims will be related to clogged printer nozzles.
Y.pmf(70)

# The probability of more than 80 of the next 300 warranty claims will be related to clogged printer nozzles.
1 - Y.cdf(80)

# The probability of more Determine the likelihood that between 75 and 90 of the next 300 warranty claims will be related to clogged printer nozzles.
# (As a note, when we say "between", that means we should include 75 and 90 in the calculation.)
Y.cdf(90) - Y.cdf(74)